
package se;

public class FrMain extends javax.swing.JFrame {

    /**
     * Creates new form FrMain
     */
    public FrMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelMonHoc = new javax.swing.JPanel();
        panelGiangVien = new javax.swing.JPanel();
        panelXayDungCTDT = new javax.swing.JPanel();
        panelBaoCao = new javax.swing.JPanel();
        panelTaiKhoan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setName(""); // NOI18N

        javax.swing.GroupLayout panelMonHocLayout = new javax.swing.GroupLayout(panelMonHoc);
        panelMonHoc.setLayout(panelMonHocLayout);
        panelMonHocLayout.setHorizontalGroup(
            panelMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        panelMonHocLayout.setVerticalGroup(
            panelMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Môn học", new javax.swing.ImageIcon(getClass().getResource("/se/icon/rsz_books-icon-512.png")), panelMonHoc); // NOI18N

        javax.swing.GroupLayout panelGiangVienLayout = new javax.swing.GroupLayout(panelGiangVien);
        panelGiangVien.setLayout(panelGiangVienLayout);
        panelGiangVienLayout.setHorizontalGroup(
            panelGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        panelGiangVienLayout.setVerticalGroup(
            panelGiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Giảng viên", new javax.swing.ImageIcon(getClass().getResource("/se/icon/rsz_1office-client-male-light-icon.png")), panelGiangVien); // NOI18N

        javax.swing.GroupLayout panelXayDungCTDTLayout = new javax.swing.GroupLayout(panelXayDungCTDT);
        panelXayDungCTDT.setLayout(panelXayDungCTDTLayout);
        panelXayDungCTDTLayout.setHorizontalGroup(
            panelXayDungCTDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        panelXayDungCTDTLayout.setVerticalGroup(
            panelXayDungCTDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Xây dựng CTDT", new javax.swing.ImageIcon(getClass().getResource("/se/icon/rsz_partition-magic-icon.png")), panelXayDungCTDT); // NOI18N

        javax.swing.GroupLayout panelBaoCaoLayout = new javax.swing.GroupLayout(panelBaoCao);
        panelBaoCao.setLayout(panelBaoCaoLayout);
        panelBaoCaoLayout.setHorizontalGroup(
            panelBaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        panelBaoCaoLayout.setVerticalGroup(
            panelBaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Báo cáo", new javax.swing.ImageIcon(getClass().getResource("/se/icon/rsz_black-my-documents.png")), panelBaoCao); // NOI18N

        javax.swing.GroupLayout panelTaiKhoanLayout = new javax.swing.GroupLayout(panelTaiKhoan);
        panelTaiKhoan.setLayout(panelTaiKhoanLayout);
        panelTaiKhoanLayout.setHorizontalGroup(
            panelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        panelTaiKhoanLayout.setVerticalGroup(
            panelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tài khoản", new javax.swing.ImageIcon(getClass().getResource("/se/icon/rsz_users_folder_black.png")), panelTaiKhoan); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelBaoCao;
    private javax.swing.JPanel panelGiangVien;
    private javax.swing.JPanel panelMonHoc;
    private javax.swing.JPanel panelTaiKhoan;
    private javax.swing.JPanel panelXayDungCTDT;
    // End of variables declaration//GEN-END:variables
}
